server:
  servlet:
    context-path: /ztkyn
spring:
  jackson:
    default-property-inclusion: NON_NULL #不为空的属性才会序列化,具体属性可看JsonInclude.Include
    deserialization:
      fail-on-unknown-properties: false  # 常用,json中含pojo不存在属性时是否失败报错,默认true
    serialization:
      FAIL_ON_EMPTY_BEANS: true # 对象为空时是否报错，默认true
springdoc:
  swagger-ui:
    enabled: true
